### PR TITLE
LPS-62205 Move the code to receive a notification of changing a configuration to another component so avoid the portlet to be redeployed

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Guys,

Technically this is fine, nothing prevents you to do that.

However, adding the dynamism to your portlet your code will get more complicated, since you will need to handle the situations where this configuration, potentially, won't be available

**Comment by marcellustavares** [comment]
Hey @migue, 

Actually this was not our first intention, we're just trying to bypass the issue we discussed about. I'm not sure even if Brian would accept this since no other portlet is doing the same.

Should we try to push this fwd?

Thanks

**Comment by migue** [comment]
I know, I know

If you are ok with it, and you are up to deal with the complexities it
could bring you guys in the future, I see no problem trying to move forward
:)

On 11 February 2016 at 14:09, Marcellus Tavares <notifications@github.com>
wrote:

> Hey @migue <https://github.com/migue>,
>
> Actually this was not our first intention, we're just trying to bypass the
> issue we discussed about. I'm not sure even if Brian would accept this
> since no other portlet is doing the same.
>
> Should we try to push this fwd?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/migue/liferay-portal/pull/651#issuecomment-182857421>.
>



-- 
Un saludo,

Migue

http://migue.github.io

**Pull request closed without merging**
