### PR TITLE
LPS-64764 Fix portal context path when different than ROOT

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
For first commit, I wanted to mean: "Exit fast" :smile:

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/mdelapenya/liferay-portal/pull/520. [See changes here.](https://github.com/migue/liferay-portal/compare/f948c47~1...f948c47) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38472. [See changes here.](https://github.com/migue/liferay-portal/compare/5b472b3~1...5b472b3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
