### PR TITLE
LPS-67296 Move more sql code generation to the single-responsibility class

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:stop

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43072. [See changes here.](https://github.com/migue/liferay-portal/compare/59bf7d9~1...59bf7d9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43073. [See changes here.](https://github.com/migue/liferay-portal/compare/65e8e96~1...65e8e96) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43115. [See changes here.](https://github.com/migue/liferay-portal/compare/979070c~1...979070c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43191. [See changes here.](https://github.com/migue/liferay-portal/compare/062125a~1...062125a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
