### PR TITLE
Lps 59076

### PR DESCRIPTION
**Pull request by shuyangzhou**
Hey guys @brianchandotcom @rotty3000 @hhuijser @peterfellwock

This is an example change for the @Component to Spring bean converation we talked about on the email thread @peterfellwock started titled "Shopping portlet circular dependency"

It has been a while, so I guess our memory on this are all getting blurry to some degree. So let me recap a bit.

This started by @hhuijser 's SF change that automatically convert *ServiceUtil to @Reference injection. In the shopping service case, it creates a circular dependency between OSGi @Component and Spring Extender @ServiceReference. If you don't remember the exact circular dependency case, please refer back to the email. I am not trying repeat it here.

So the solution is, OSGi services from the same bundle should always avoid cross reference each other between @Components and Spring beans. They can be all @Components @Reference each other, or all Spring bean @BeanReference each other, but no mix usage.

This limitation only applies to OSGi services within the same bundle. For services across bundles, they should always do @Reference, which are all fixed by @hhuijser.

@hhuijser has creation a SF scanning logic to pick up the offending cases, you can run it by doing "ant format-source -Dsource.formatter.check.modules.service.util=true".
There are tons of them, to make an example refactor, I picked the same shopping case. SF output like this:
```
     [java] LPS-59076: Convert OSGi Component to Spring bean: ./modules/apps/shopping/shopping-service/src/main/java/com/liferay/shopping/model/listener/GroupModelListener.java
     [java] LPS-59076: Convert OSGi Component to Spring bean: ./modules/apps/shopping/shopping-service/src/main/java/com/liferay/shopping/model/listener/UserModelListener.java
     [java] LPS-59076: Convert OSGi Component to Spring bean: ./modules/apps/shopping/shopping-service/src/main/java/com/liferay/shopping/service/permission/ShoppingCategoryPermission.java
     [java] LPS-59076: Convert OSGi Component to Spring bean: ./modules/apps/shopping/shopping-service/src/main/java/com/liferay/shopping/service/permission/ShoppingItemPermission.java
     [java] LPS-59076: Convert OSGi Component to Spring bean: ./modules/apps/shopping/shopping-service/src/main/java/com/liferay/shopping/service/permission/ShoppingOrderPermission.java

```

I manually converted all offending OSGi @Components to Spring beans, and checked to make sure the "circular dependency" is really gone. The shopping-service now loads correctly, and no test is failing.

The purpose of this pull is just a style checking with @migue and @rotty3000, if you are both ok with this style changing, @hhuijser can take care the rest of heavy job to fix all offending cases.

Thanks guys, please give us some feedback on this, either we move on with it, or trying something else you are going to offer.

Shuyang

### CODE REVIEW

**Comment by migue** [comment]
Guys,

The code seems perfectly fine to me. If this is the direction you wanna take, you can go ahead and merge it. I am not gonna fight it, but I don't agree with it.

My major concern is that we are promoting bad designs. I know we decided in the past to allow circular dependencies within our Spring contexts, but it does not mean this was idea. However, IMHO, we're promoting it by doing this.

Before merging it I would like to highlight that this issue has nothing to do with services/beans being on the same module or not. If you have a bean B with a reference to an OSGi service S, and the OSGi service S has a reference back to the bean B you will get a deadlock independently where the bean and the service had been designed.

Thanks you very much!

**Comment by shuyangzhou** [comment]
Yes, @migue, you are right on that. Circular dependency is never a good thing. But the problem is, it is legacy, we have that for too long in too many places. As much as I would like to get rid of it as you do, it is not practical to do such a massive change for that at this moment.

We just need a way to overcome the current issue, and this is not really making things worse, it is just as bad as it used to be :(

For the long run, I agree we need to rip off the circular dependency all together, but we need to figure out a way to do it more gradually, piece by piece, to lower the impact to the whole system.

Since you are ok with this, I will just resend it to @brianchandotcom , so he can merge in, and when @hhuijser wakes up, he can just continue the process.

@rotty3000, did you have a chance to check it yet? If you are not objecting on this, we will move on with it.

Thanks

Shuyang

**Comment by shuyangzhou** [comment]
Resent to @brianchandotcom at https://github.com/brianchandotcom/liferay-portal/pull/32278

**Comment by shuyangzhou** [comment]
Sorry, rebase error, resent at https://github.com/brianchandotcom/liferay-portal/pull/32279

**Comment by peterfellwock** [comment]
@migue @shuyangzhou lets identify the two core issues here:

1. We are marrying two "service" deploying technologies which are cross referencing each other with circular dependencies causing deadlocks.

2. We have in the past allowed circular dependencies within Spring that we have not had to deal with until now.

I am not clear to the solutions and if really there are any without a major overhaul. I suggest we use @shuyangzhou pattern for shopping and stabilize and move from this. 

In regards to #1, @migue is it possible to stage the deployment order so we can actually expect all Spring services to be loaded and then all OSGi services to then be loaded? Or is the solution a overhaul to move away from Spring and make ServiceBuilder pump out everything in OSGi Services?

**Pull request closed without merging**
