### PR TITLE
LPS-64764 Fix paths when using an application context other than ROOT

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by migue** [comment]
Manu,

this is ready to review then?

**Comment by mdelapenya** [comment]
Yes, it's ready 👍

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/mdelapenya/liferay-portal/pull/526. [See changes here.](https://github.com/migue/liferay-portal/compare/2d9015f~1...2d9015f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
