### PR TITLE
LPS-69720 Replicate logic so that we can release it

### PR DESCRIPTION
**Pull request by adolfopa**
@migue The last commit is an exercise on copy & paste, but it is necessary so that these changes can be included in the release of the Twitter portlet (needs to be working on GA3).

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
@migue The autoclose was bogus. SF is complaining that I'm missing an `@Override` annotation in the `getNamespace()` method, but the fact is that the `getNamespace()` method does not exist in version 2.4.0 (that class is overriding an older version on purpose, see latest commit). Not sure if its better to make SF ignore that particular line, or to rename the `getNamespace()` method so that SF does not complain.

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
See https://github.com/migue/liferay-portal/pull/925

**Pull request closed without merging**
