### PR TITLE
LPS-69276 Convert to nvarchar if running against MS SQL Server

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:reopen

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:reopen

**Comment by migue** [comment]
Seems like an real semantic versioning error, doesn't it?

**Comment by mdelapenya** [comment]
Resent here: https://github.com/migue/liferay-portal/pull/909

**Pull request closed without merging**
