### PR TITLE
LPS-63828 changes needed to pass source formatter

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @migue this pull is about a new dev workflow that frontend guys would like.  Here is the workflow that this pull enables. Basically from their frontend tasks they want to be able to build a theme and then install it into liferay as a directory and have portal automatically see new changes to files in the build directory immediately.

So I've implemented this by adding a new url handler "webbundledir" and then auto-deploying the directory directly (no temp copying) and then invoking the Equinox Reference url handler on the file url directly.  

Some of this may be a bit hack-ish where I'm subclassing WabProcessor, etc, please let me know if you want me to refactor anything here.

Thanks.

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Hey Greg,

I ran out of time today (almost midnight) so didn't get the chance to do an in-depth review. My first look at it:

* It's really nice you've added this support
* I am "concerned" about adding a direct dependency from the WAB module to the Equinox implementation. I know we are using Equinox, but I would like not to create this dependency.
* Said that, this is a development tool, so I am thinking we could create a new module, and try to reuse the existing functionality through service composition.

I will give a deeper look tomorrow early morning, ad we can talk to each other and see what the final solution should be.

Thank you very much Greg!!!

**Comment by gamerson** [comment]
Sounds good Miguel chat with you tomorrow.

On Thu, Mar 3, 2016 at 4:28 PM, Miguel Ángel Pastor Olivar <
notifications@github.com> wrote:

> Hey Greg,
>
> I ran out of time today (almost midnight) so didn't get the chance to do
> an in-depth review. My first look at it:
>
>    - It's really nice you've added this support
>    - I am "concerned" about adding a direct dependency from the WAB
>    module to the Equinox implementation. I know we are using Equinox, but I
>    would like not to create this dependency.
>    - Said that, this is a development tool, so I am thinking we could
>    create a new module, and try to reuse the existing functionality through
>    service composition.
>
> I will give a deeper look tomorrow early morning, ad we can talk to each
> other and see what the final solution should be.
>
> Thank you very much Greg!!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/migue/liferay-portal/pull/710#issuecomment-191995297>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
sent new pull #718

**Pull request closed without merging**
