### PR TITLE
[TECHNICAL-SUPPORT] LPS-67176

### PR DESCRIPTION
**Pull request by sergiogonzalez**
/cc @Alec-Shay

From Alec:

>https://issues.liferay.com/browse/LPS-67176
https://issues.liferay.com/browse/LPP-21931

>Refactored to use PropsValues for the properties, and added a configuration for the connection timeout.

>There is another setting we can add to the ClientConfiguration, which is for the max connections. However, I didn't know whether it would be better to use the http.impl.max.connections.per.host property or the http.impl.max.total.connections property, since I don't know how we would want to handle this, so I left it out.

> Although we allow configuring Liferay with a forward proxy, we have not implemented using it with S3, although clients should be able to expect this. Some clients must connect using a proxy.

> I implemented it with just the basic configurations (copied the logic of using different proxy authorization types from HttpImpl), but it's possible there are more configuration options we could add as well that I just wasn't sure whether we already have options for, as I noted on the LPS (the web.server.protocol property?). I tested using Apache web server for a proxy, and enabling it as a proxy and for using HTTPS (which seems to be the default S3 will use).

### CODE REVIEW

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Hi guys,

This is not the proper fix. The S3 related configuration is defined here `com.liferay.portal.store.s3.configuration.S3StoreConfiguration` and we should define all the required configuration in this class.

Trying tho use the portal properties will create an unnecessary dependency between the module and the portal, not to say that we will be forcing all the Http requests made by the portal to go through the proxy even if we just want the proxy behaviour enabled for the S3 client.

Not sure if you want me to make the change of you prefer to do it. I will keep this pull open for now.

**Comment by Alec-Shay** [comment]
@migue I'm not sure I understand what you mean by creating an "unnecessary dependency between the module and the portal." What's unnecessary about it? I see many other modules doing the same to allow for any sort of configuration, and the portal properties are the only place this can be configured in this way.

Or are you suggesting a separate property specifically for using a proxy with S3?

**Comment by migue** [comment]
@Alec-Shay it's unnecessary in the sense that the S3 store does not need anything from the portal impl module, because you don't really need to read the configuration from the portal.

What I am just suggesting is to use the existing configuration defined here ``com.liferay.portal.store.s3.configuration.S3StoreConfiguration`` and add the required fields

 If we take this approach we will be able to configure the proxy for the S3Store independently from the portal proxy.

**Comment by Alec-Shay** [comment]
@migue Thanks for clarifying. I actually meant to comment again that I realized what you meant, I've been working on changing the implementation. I just tested it and will send an updated pull for review shortly.

**Comment by jonathanmccann** [comment]
Resent https://github.com/migue/liferay-portal/pull/831

**Pull request closed without merging**
