### PR TITLE
Split SQLTransformer logic into specific database transformations

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:reopen

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/mdelapenya/liferay-portal/pull/543. [See changes here.](https://github.com/migue/liferay-portal/compare/f2f5355~4...f2f5355) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
