### PR TITLE
LPS-58170 Fix classloading composition when using allowed classes from Freemarker templates

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
Working on fixing the tests. Will send a commit soon

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/mdelapenya/liferay-portal/pull/512. [See changes here.](https://github.com/migue/liferay-portal/compare/f1b2304~5...f1b2304) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/mdelapenya/liferay-portal/pull/513. [See changes here.](https://github.com/migue/liferay-portal/compare/3918d77~6...3918d77) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/mdelapenya/liferay-portal/pull/514. [See changes here.](https://github.com/migue/liferay-portal/compare/f3d268a~5...f3d268a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
