### PR TITLE
LPS-70309 Fixes Soy renderer thread safety

### PR DESCRIPTION
**Pull request by brunobasto**
Hey @migue,

I've put together your PR to @jbalsas (https://github.com/jbalsas/liferay-portal/pull/688) and another one from @shinnlok (https://github.com/brunobasto/liferay-portal/pull/818). I reverted the usage of Jackson just because I don't know how to use it to match our use case. We don't want to always convert the value to a Map. Instead, we want the deserializer to be smart enough so that it knows that if the json has a `"string like this"` it will convert to `java.lang.String`, if it's `{key: "value"}` it'll convert to a HashMap and if it's `["an array"]` it will convert to a list of strings or an array. And it does so recursively so that, {key: {nested: { obj: "value" }}} is also converted to a HashMap of a HashMap of a HashMap that contains a String. I didn't look too much, but probably Jackson has already a builtin tool to that that. I couldn't find examples. I did some basic load test with jMeter, and didn't see any exceptions raise with those changes applied.

### CODE REVIEW

**Comment by brunobasto** [comment]
@jbalsas, I've also removed the ThemeDisplay from the Soy context. Should I put that into a separated PR? Also, should we log this somewhere as a kind of braking change?

**Comment by jbalsas** [comment]
Yeah, maybe we can't simply do the breaking change, as much as we'd like to :)

What if we create a ContextContributor instead? Then, things will work the same way and `ThemeDisplay` will be included in the context by default (without breaking anything). This way, it's very easy for us to document the performance-tuning improvement of simply stopping that component.

Once we are ready to release 7.1, we might do the opposite: disable the component by default and advise people wanting that old behaviour to enable it back.

What do you think?

**Comment by brunobasto** [comment]
Sounds good to me 👍

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
We've already talked about it, and it's already merged

**Pull request closed without merging**
