### PR TITLE
LPS-58170 Fix classloading composition when using allowed classes from Freemarker templates

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
@migue, failures are produced because it seems it's not taking into account the `update` method of the module configuration. For instance:

```
[exec] com.liferay.portal.template.freemarker.test.LiferayTemplateClassResolverTest > testResolveAllowedPortalClass FAILED
     [exec]     freemarker.template.TemplateException: Instantiating com.liferay.portal.kernel.model.User is not allowed in the template for security reasons
     [exec]         at com.liferay.portal.template.freemarker.LiferayTemplateClassResolver.resolve(LiferayTemplateClassResolver.java:124)
     [exec]         at com.liferay.portal.template.freemarker.test.LiferayTemplateClassResolverTest.testResolveAllowedPortalClass(LiferayTemplateClassResolverTest.java:161)
```
when we explicitly set the properties on the test method.

I'm going to add a commit logging a trace in the modified method of the component to verify it.

**Comment by mdelapenya** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Manu, just wrote some comments in a couple of commits.

In addition, tests are failing (the ones on the module we are changing).

Let's try to go through it tomorrow early morning?

Thx!

**Comment by mdelapenya** [comment]
ci:retest

**Pull request closed without merging**
