### PR TITLE
Add companyId as a column in all portal tables (except for the control tables)

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by migue** [comment]
Seems ok now?

**Comment by cgoncas** [comment]
I think it is ok. But there are a problem in the 14th node. I don't know why it is not compiling there. I have writen a mail to Kiyoshi, so he can help me.

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Pull request closed without merging**
