### PR TITLE
[TECHNICAL-SUPPORT] LPS-71825

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Tests are failing, could you please take a look?

**Comment by mbowerman** [comment]
Hi @migue,

Please see https://github.com/migue/liferay-portal/pull/982.

**Comment by mbowerman** [comment]
ci:close

**Pull request closed without merging**
