### PR TITLE
LPS-68054 Use message count as only criterion

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @migue 

I'm sending this to you because this upgrade seems to be a bit unconventional (I haven't found any other case where temp tables are used). Also, my main concern here is about how to avoid name collisions when creating the temp table. I've given it a long, weird name, but I'm not sure if that's acceptable.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43635. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
