### PR TITLE
LPS-58771 Updates tests

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:stop

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
ci:reopen

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brunobasto/liferay-portal/pull/832. [See changes here.](https://github.com/migue/liferay-portal/compare/25a580182944~4...25a580182944) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
