### PR TITLE
Add companyId to all the partitionable tables

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
@cgoncas 

Seems some of the failures are real failures, aren't they?

We can take a look tomorrow morning! Ping me in the morning!

**Comment by cgoncas** [comment]
ci:retest

**Pull request closed without merging**
