### PR TITLE
LPS-64979 Add IBM crypto packages to OSGi's system.extra

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
Migue, Kenji is reviewing the potential JBoss issues on their environments, so not sure if we could wait for his findings

**Comment by kenjiheigel** [comment]
@alee8888 @mdelapenya @migue, it looks like there might be some actual issues with this update. 

Here are a few things I noticed from the tests off the bat. I'm going to retest it to be sure though. 

1. After clicking the "Select File" button on the Blogs add form:
after2
2. After navigating to the "Add Data Definition" form in the DDL portlet:
after0
3. Navigating to Web Content through the Product Menu throws this error:
```
[exec] 21:44:55,792 ERROR [http-nio-8080-exec-5][IncludeTag:128] Current URL /group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureKey=BASIC-WEB-CONTENT&_com_liferay_journal_web_portlet_JournalPortlet_groupId=30973&_com_liferay_journal_web_portlet_JournalPortlet_redirect=http%3A%2F%2Fcloud-10-0-16-44.lax.liferay.com%3A8080%2Fgroup%2Fguest%2F~%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_journal_web_portlet_JournalPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_p_mode%3Dview%26p_p_auth%3DXR7HI9cn&_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&_com_liferay_journal_web_portlet_JournalPortlet_folderId=0&p_p_auth=XR7HI9cn generates exception: An exception occurred processing JSP page /html/taglib/ui/form_navigator/lexicon/sections.jspf at line 37
     [exec] 
     [exec] 34: 			<aui:fieldset id="<%= _getSectionId(formNavigatorEntry.getKey()) %>">
     [exec] 35: 
     [exec] 36: 				<%
     [exec] 37: 				PortalIncludeUtil.include(
     [exec] 38: 					pageContext,
     [exec] 39: 					new PortalIncludeUtil.HTMLRenderer() {
     [exec] 40: 
     [exec] 
     [exec] 
     [exec] Stacktrace:
     [exec] java.lang.ClassNotFoundException: com.liferay.portal.kernel.util.PropsUtil cannot be found by com.liferay.petra.encryptor_1.0.0
     [exec] 	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:444)
     [exec] 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:357)
     [exec] 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:349)
     [exec] 	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
     [exec] 	at com.liferay.petra.encryptor.Encryptor.<clinit>(Encryptor.java:53)
     [exec] 	at org.apache.jsp.alloyeditor_jsp._jspService(alloyeditor_jsp:215)
     [exec] 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
     [exec] 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
     [exec] 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.JspServlet.service(JspServlet.java:376)
     [exec] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.JspServlet.service(JspServlet.java:387)
     [exec] 	at com.liferay.portal.osgi.web.servlet.context.helper.internal.JspServletWrapper.service(JspServletWrapper.java:70)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:50)
     [exec] 	at com.liferay.portal.osgi.web.servlet.context.helper.internal.ServletContextHelperRegistrationImpl$RestrictPortletServletRequestFilter.doFilter(ServletContextHelperRegistrationImpl.java:444)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.FilterRegistration.doFilter(FilterRegistration.java:121)
     [exec] 19-Apr-2016 21:44:55.787 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet.service() for servlet jsp threw exception
     [exec]  java.lang.ClassNotFoundException: com.liferay.portal.kernel.util.PropsUtil cannot be found by com.liferay.petra.encryptor_1.0.0
```
Full Stacktrace:
https://gist.github.com/kenjiheigel/0eefee17da0e9929e5fbe91dc355c66e

I didn't comprehensively look at all the failures, but those were just a few I found. Let me know if you guys have any questions.

**Comment by migue** [comment]
We need to add some extra info to the bnd file. The current bnd file for
the Petra Encrypt is not 100% correct

**Comment by migue** [comment]
Could you please use this branch to do your testing?
https://github.com/migue/liferay-portal/tree/pr-771

On 20 April 2016 at 01:37, Miguel Angel Pastor Olivar <
miguelinlas3@gmail.com> wrote:

> We need to add some extra info to the bnd file. The current bnd file for
> the Petra Encrypt is not 100% correct
> On Apr 19, 2016 6:35 PM, "Kenji Heigel" <notifications@github.com> wrote:
>
>> @alee8888 <https://github.com/alee8888> @mdelapenya
>> <https://github.com/mdelapenya> @migue <https://github.com/migue>, it
>> looks like there might be some actual issues with this update.
>>
>> Here are a few things I noticed from the tests off the bat. I'm going to
>> retest it to be sure though.
>>
>>    1. After clicking the "Select File" button on the Blogs add form: [image:
>>    after2]
>>    <https://cloud.githubusercontent.com/assets/2567802/14658820/95a6e3f6-064b-11e6-864c-746802dc9745.jpg>
>>    2. After navigating to the "Add Data Definition" form in the DDL
>>    portlet: [image: after0]
>>    <https://cloud.githubusercontent.com/assets/2567802/14658837/b48711d8-064b-11e6-8777-997d7a5a8084.jpg>
>>    3. Navigating to Web Content through the Product Menu throws this
>>    error:
>>
>> [exec] 21:44:55,792 ERROR [http-nio-8080-exec-5][IncludeTag:128] Current URL /group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureKey=BASIC-WEB-CONTENT&_com_liferay_journal_web_portlet_JournalPortlet_groupId=30973&_com_liferay_journal_web_portlet_JournalPortlet_redirect=http%3A%2F%2Fcloud-10-0-16-44.lax.liferay.com%3A8080%2Fgroup%2Fguest%2F~%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_journal_web_portlet_JournalPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_p_mode%3Dview%26p_p_auth%3DXR7HI9cn&_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&_com_liferay_journal_web_portlet_JournalPortlet_folderId=0&p_p_auth=XR7HI9cn generates exception: An exception occurred processing JSP page /html/taglib/ui/form_navigator/lexicon/sections.jspf at line 37
>>      [exec]
>>      [exec] 34:             <aui:fieldset id="<%= _getSectionId(formNavigatorEntry.getKey()) %>">
>>      [exec] 35:
>>      [exec] 36:                 <%
>>      [exec] 37:                 PortalIncludeUtil.include(
>>      [exec] 38:                     pageContext,
>>      [exec] 39:                     new PortalIncludeUtil.HTMLRenderer() {
>>      [exec] 40:
>>      [exec]
>>      [exec]
>>      [exec] Stacktrace:
>>      [exec] java.lang.ClassNotFoundException: com.liferay.portal.kernel.util.PropsUtil cannot be found by com.liferay.petra.encryptor_1.0.0
>>      [exec]     at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:444)
>>      [exec]     at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:357)
>>      [exec]     at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:349)
>>      [exec]     at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
>>      [exec]     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
>>      [exec]     at com.liferay.petra.encryptor.Encryptor.<clinit>(Encryptor.java:53)
>>      [exec]     at org.apache.jsp.alloyeditor_jsp._jspService(alloyeditor_jsp:215)
>>      [exec]     at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
>>      [exec]     at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
>>      [exec]     at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
>>      [exec]     at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
>>      [exec]     at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
>>      [exec]     at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
>>      [exec]     at com.liferay.portal.osgi.web.servlet.jsp.compiler.JspServlet.service(JspServlet.java:376)
>>      [exec]     at com.liferay.portal.osgi.web.servlet.jsp.compiler.JspServlet.service(JspServlet.java:387)
>>      [exec]     at com.liferay.portal.osgi.web.servlet.context.helper.internal.JspServletWrapper.service(JspServletWrapper.java:70)
>>      [exec]     at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
>>      [exec]     at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:50)
>>      [exec]     at com.liferay.portal.osgi.web.servlet.context.helper.internal.ServletContextHelperRegistrationImpl$RestrictPortletServletRequestFilter.doFilter(ServletContextHelperRegistrationImpl.java:444)
>>      [exec]     at org.eclipse.equinox.http.servlet.internal.registration.FilterRegistration.doFilter(FilterRegistration.java:121)
>>      [exec] 19-Apr-2016 21:44:55.787 SEVERE [http-nio-8080-exec-5] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet.service() for servlet jsp threw exception
>>      [exec]  java.lang.ClassNotFoundException: com.liferay.portal.kernel.util.PropsUtil cannot be found by com.liferay.petra.encryptor_1.0.0
>>
>> Full Stacktrace:
>> https://gist.github.com/kenjiheigel/0eefee17da0e9929e5fbe91dc355c66e
>>
>> I didn't comprehensively look at all the failures, but those were just a
>> few I found. Let me know if you guys have any questions.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/migue/liferay-portal/pull/771#issuecomment-212171372>
>>
>


-- 
Un saludo,

Migue

http://migue.github.io

**Comment by kenjiheigel** [comment]
@migue, ahh ok. Thanks for the update. I'm rerunning CI off of the branch you link here:
https://github.com/kenjiheigel/liferay-portal/pull/188

I was also able to reproduce the issues on JBoss and Wildfly. I'm currently trying to test the workarounds. 

After that, I'll build some JBoss and Wildfly bundles off of that branch if the CI results for it are good, and test those on the IBM JDK environments.

**Comment by migue** [comment]
Pull request submitted to https://github.com/mdelapenya/liferay-portal/pull/525. [See changes here.](https://github.com/migue/liferay-portal/compare/496cfc1~1...496cfc1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
