### PR TITLE
LPS-55107 Empty cells of Wiki Creole tables are not shown in all views (switching back to non-breaking space)

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @migue 

Could you please check this pull?

I re-added the non-breaking space "&nbsp;" character because the empty space " " will not get rendered by the browser.

Best regards,
István

### CODE REVIEW

**Comment by migue** [comment]
We will need to fix the tests and check if the PMD tool is not ignoring the generated source files.

I can do both, but hopefully, I will start my paternity leave tomorrow, so expect some delay on it :D

**Comment by IstvanD** [comment]
Hey @migue 

I hope you are doing well and you enjoyed your paternity leave. :smile: 

I was wondering, did you had the opportunity to take a look at those issues with the tests?

Thank you!

**Comment by migue** [comment]
Sorry Istvan,

Getting up to speed (I've been travelling during the last 2 weeks) and I am trying to catch up on the pending pulls ... at some point later this week should be able to revisit this pull.

Sorry for the delay

**Comment by IstvanD** [comment]
Thank you Miguel.

**Comment by IstvanD** [comment]
Hey Miguel,

I hope you're doing well.

Did you managed to take some time to revisit the pull?

Thanks!

**Comment by migue** [comment]
Hey Itsvan,

Reviewing the pull again I have a few concerns:

* I don't think the line `cn.add(new UnformattedTextNode(StringEscapeUtils.unescapeHtml("&nbsp;")));` is fine because we are mixing 2 completely different things: the construction of the AST and the conversion to HTML (the grammar knows nothing about HTML, and, with this new change, we are coupling it to it.

* Tests are failing with your original pull.

I think that handling the conversion in the Visitors instead of the grammar would be more accurate. In addition, do we really need the dependency on the StringEscapeUtils?

What do you think?

**Comment by IstvanD** [comment]
Hey Miguel,

Thank you for your thoughts.

I tried to implement a solution in the Visitor previously, but since it was not possible there to apply a rule which handles table cells properly (for example handling cell boundaries), I resorted to solve this on the grammar site.

Also, I tried several approaches for constructing a proper non-breaking space, with avoiding third-party dependencies in mind, but, unfortunately, StringEscapeUtils was the only tool which was able to create a space character which remained in the table cell in the rendered Wiki article.

**Comment by migue** [comment]
Do we need only to do that only when we are in the a table cell? I mean, could we do that on every blank space?

**Comment by IstvanD** [comment]
Hi Miguel,

Originally, the customer wanted to create partially filled tables, which contain both empty and non-empty cells.
His concern was that if, for example, he enters text in the first and last column in a 9X9 table, leaving the cells in the middle column empty, the table "implodes" eg. there will be no space that separates the text between the first and last columns, and it will appear that the two texts form one single word.

The non breaking spaces were necessary to keep the filled cells properly apart from each other.

**Comment by IstvanD** [comment]
Hi Miguel,

As the time being, I could not find another solution for this issue.
Could you please take another look at it?

Thank you!

Best regards,
István

**Pull request closed without merging**
