### PR TITLE
LPS-65755 Copy Company table to non-principal shards

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39711. [See changes here.](https://github.com/migue/liferay-portal/compare/8c9a62f~3...8c9a62f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
