### PR TITLE
LPS-59047 Orphaned Subscription records stay in the database even after applying LPS-45418

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by migue** [comment]
Hey guys,

Some "concerns":

* Is there any specific reason this has to be a verifier? I think this should be an upgrade process. Adding this behaviour in a verifier means the original root cause has not been fixed?

* We don't know in advance how big this dataset could be, retrieving it and executing the delete one by one could be, potentially, a huge and costly operation. couldn't it?

* Tests are failing: is this just a problem of the CI or it is caused by the changes included within this pull?

**Comment by sergiogonzalez** [comment]
Hey @IstvanD can you take a look at @migue comments?

**Comment by IstvanD** [comment]
Hi Guys,

Thank you for your feedback!

Addressing your concerns:

1. There was an issue, LPS-45418, regarding Subscriptions made on the Asset Publisher portlet.
Prior applying LPS-45418, if an Asset Publisher portlet was removed from a page, only the portletPreferences linked to the Subscriptions were deleted, but not the subscription entries themselves. After LPS-45418, both these entries are deleted with removal of the AP portlet, however, the subscriptions with no corresponding Portlet Preference (which were created prior LPS-45418) remain in the database and cause an error in the My Subscriptions portlet.
With LPS-45418 there is no chance for creating orphaned Subscription entries, but LPS-45418 will not remove these entries subsequently, once they are in the database. 
So I thought about a cleanup process which will purge this orphaned entries. so they wont cause any no errors in the My Subscriptions portlet. Because LPS-45418 is appearing only on 6.2 and upwards, I saw no point to put this cleanup script to an Upgrade process, but I might be wrong.

2. Yes, if the database and the portletPreferences table in particular is huge, it can take some time to query through it, but I assume that the number of erroneous Subscriptions will be small, because they are generated in a very special case (see above). There might be a way to make these queries more optimized, but the time being I can't think of any such a way.

3. I checked the tests, and as I see, the failed tests are related to handling Wiki Nodes, and not related to P ortlet Preferences and Subscriptions.

Best regards,
István

**Comment by IstvanD** [comment]
Hi @sergiogonzalez , @migue 

A similar issue to LPS-45418 apperated, and for solving it, it would also require to clean up the orphaned subscriptions.
https://issues.liferay.com/browse/LPS-60895

However, if the current fix is not available, we cannot proceed with the solution of LPS-60895, because the orphaned subscription would still remain in the database, and cause errors.

Could you please process this pull request further?

Thank you!

Best regards,
István

**Comment by migue** [comment]
Hi @IstvanD ,

As I already told you, I don't think this is the right solution, at least for merging it in master.

**Comment by IstvanD** [comment]
Hi @migue 

Addressing your concerns:

1. As with LPS-45418, after fixing LPS-60895, the root cause of the orphaned subscription entries would be solved, but there would still remain entries in the database, which would cause errors in the My Subscription portlet. Therefore, some form of cleanup would be still necessary.

2. I see that the current solution may cause performance problems if the database table is particularly large. By the way, when writing VerifySubscriptions, I took VerfiyAsset as a sample which uses the same select-and-delete style query.

However, I have some alternatives for cleaning up the data:

a. instead running a SELECT SQL statement and then deleting with the API, I could use a DELETE SQL statement to delete the entries from the table
b. instead of selecting via an SQL statement, a DynamicQuery could be used, it this makes the process faster
c. if none of the above would make an optimal solution in your opinion, could you please recommend some other method? Thank you!

3. the failing of the tests are not related to the current fix.

Best regards,
István

**Comment by migue** [comment]
Hey @IstvanD ,

If the root cause have been solved, shouldn' we be able to include this as an upgrade in master? I understand you want to deliver a verifier for patch, but for the master branch we shouldn't include a verifier.

The delete approach should be way more efficient than reading-deleting.

**Pull request closed without merging**
