### PR TITLE
LPS-69360 Delete legacy resource permissions

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
@migue fallan unos tests por el format source, si lo ves bien mñna lo arreglo.

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3603. [See changes here.](https://github.com/migue/liferay-portal/compare/24bb7a9~2...24bb7a9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
