### PR TITLE
LPS-53938 Apply to the models

### PR DESCRIPTION
**Pull request by sergiosanchez**

### CODE REVIEW

**Comment by sergiosanchez** [comment]
This code comes from @achaparro who made it for 6.2.x. It has been adapted to master

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Ran out of time today, sorry. I will try to take a look tomorrow early in the morning!

Thx!

**Comment by sergiosanchez** [comment]
Hey Miguel, any updates on this? 
Thanks :)

**Comment by migue** [comment]
Should be already solved in the master branch

**Comment by sergiosanchez** [comment]
Thanks. Can you update the LPS ticket, please? ;)

**Comment by migue** [comment]
Already solved in master!

**Comment by migue** [comment]
Sorry,

I thought it was a different pull :D

Will take a look to it as soon as possible

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32711. [See changes here.](https://github.com/migue/liferay-portal/compare/a4b32b8~1...a4b32b8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
