### PR TITLE
LPS-67978 Add command upgrade:executeAll

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/28. [See changes here.](https://github.com/migue/liferay-portal/compare/8050b05~1...8050b05) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43257. [See changes here.](https://github.com/migue/liferay-portal/compare/2e9c86a~2...2e9c86a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
