### PR TITLE
LPS-64106 Support defining the index as read-only on module verifiers

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
It's been running for more than 2 hours .... :(

**Comment by migue** [comment]
Seems that tests failures are not related ... will take a deeper look tomorrow morning anyway

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
