### PR TITLE
LPS-61082 Polls Datbaseconverter

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/33685. [See changes here.](https://github.com/migue/liferay-portal/compare/4c60096~3...4c60096) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/33713. [See changes here.](https://github.com/migue/liferay-portal/compare/f02561d~6...f02561d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/33715. [See changes here.](https://github.com/migue/liferay-portal/compare/0c4a98f~6...0c4a98f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
