### PR TITLE
LPS-71623

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-71623

java.net.URLEncoder encodes spaces as "+" instead encoding them as "%20", replacing with com.liferay.portal.kernelutil.URLCodec that allows both options

### CODE REVIEW

**Comment by sharonchoi** [comment]
ci:reopen

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48061. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48065. [See changes here.](https://github.com/migue/liferay-portal/compare/9e201265abdb~1...9e201265abdb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
