### PR TITLE
SF: Remove verify Oracle

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Sorry guys, ran out of time today, I will try to take a deeper look tomorrow morning

**Comment by mdelapenya** [comment]
No problem at all @migue :smiley:

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Good morning guys,

Some comments:

* Why do you need the `@Sync` annotation?
* I don't think making the test class a child of the original Upgrade class is a good idea. Could we use composition instead?
* Will the code of the `teardown` method be executed regardless of the assume test result?

**Comment by achaparro** [comment]
Sorry, I didn't see these messages until now. I will check the point 3 today. Once I have done this, @mdelapenya will take care of points 1 and 2.

Thanks @migue .

**Pull request closed without merging**
