### PR TITLE
LPS-40590 Avoid Jackrabbit inhibits portal shutdown

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by migue** [comment]
Trying again, seems the previous execution is hung ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by migue** [comment]
Seems the tests failures are real

**Comment by mdelapenya** [comment]
They fail because of this stacktrace on afterClass.. :disappointed: 

```
junit.framework.AssertionFailedError: Thread Thread[Framework Event Dispatcher: Equinox Container: d06e1309-c1bf-0015-1dd5-ace96975d5ef,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=osgi.logging.com_liferay_configuration_admin_web, message=FrameworkEvent ERROR 
	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.endAssert(LogAssertionTestCallback.java:101)
	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.afterClass(LogAssertionTestCallback.java:162)
```

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34797. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
