### PR TITLE
[TS] LPS-69935 UserLocalService getSocialUsers generates error on PostgreSQL

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-69935

Hi Miguel,

Here's the fix for the issue we were talking about last week. Please forward to someone from the User Management team (Drew or Pei-Jung) if you agree.

Thanks!
Tibor

----
Author: @istvansajtos 
Reviewers: @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46415. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
