### PR TITLE
[TECHNICAL-SUPPORT] LPS-35823 'ant direct-deploy' does not add liferay-portlet-ext.tld

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-35823

/cc @istvansajtos

### CODE REVIEW

**Comment by lipusz** [comment]
rebased

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
rebased

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Miguel,

Please, proceed with this.

Thanks,
Tibor

@migue

**Comment by lipusz** [comment]
rebased

**Comment by lipusz** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39156. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
