### PR TITLE
Improve upgrade performance adding a index

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/218. [See changes here.](https://github.com/migue/liferay-portal/compare/e252d39~1...e252d39) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
