### PR TITLE
LPS-61082: Make ConverDatabase extensible with OSGi

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Cris, ran out of time today and I would like to talk to you before doing some changes on the tests ... Let's try to get an slot tomorrow and go through it, please.

¡Thank you very much!

**Comment by migue** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/180. [See changes here.](https://github.com/migue/liferay-portal/compare/1c064b9~1...1c064b9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
