### PR TITLE
Recreate index when column name has parameters

### PR DESCRIPTION
**Pull request by achaparro**
@marianoalvarosaiz, could you verify that there was a typo here?:
https://github.com/migue/liferay-portal/commit/dc5d478b23f0eddd3de939add620218be4bb3aae

@migue, once Mariano answers that, you could proceed with the revision.

Thanks!

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
@achaparro that's right. Thanks!

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44676. [See changes here.](https://github.com/migue/liferay-portal/compare/3f3fc76~2...3f3fc76) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44679. [See changes here.](https://github.com/migue/liferay-portal/compare/e4699db~1...e4699db) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44685. [See changes here.](https://github.com/migue/liferay-portal/compare/c4fc107~2...c4fc107) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
