### PR TITLE
LPS-61577 Change references to the annotation

### PR DESCRIPTION
**Pull request by JorgeFerrer**
Hola Migue, Estos son los cambios para mover la anotación para añadir metainformación a los Configuration objects a su propio módulo. Parece que todo funciona. Sólo faltaría ver si queremos hacer más cambios en el resto de módulos de configuration-admin ahora que tenemos bnd3

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by migue** [comment]
Ran out of time today Jorge, will try to take a look to it early in the morning tomorrow.

A just took a quick look to it and everything seems fine, but I will take a deeper look tomorrow.

Thanks a lot!

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Sent to Brian as https://github.com/brianchandotcom/liferay-portal/pull/34416

**Pull request closed without merging**
