### PR TITLE
LPS-69824

### PR DESCRIPTION
**Pull request by eperezg**

### CODE REVIEW

**Comment by eperezg** [comment]
cc  @jonathanmccann
Comes from https://github.com/jonathanmccann/liferay-portal/pull/1163, I could not use autocloseable try catch statement due to parser error. As this is a support fix that is also going to be backported, I think current solution should be ok.

**Comment by eperezg** [comment]
ci:reopen

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45806. [See changes here.](https://github.com/migue/liferay-portal/compare/b96bbae~2...b96bbae) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
