### PR TITLE
Fix WARNS for ResourceActions in Upgrade

### PR DESCRIPTION
**Pull request by cgoncas**
/cc @achaparro

### CODE REVIEW

**Comment by achaparro** [comment]
Hey @migue,

I have just realized that this pull request seems to have the same purpose that mine here:
https://github.com/migue/liferay-portal/pull/635

Please, take that into account after selecting one to solve the issue.

Thanks!
@migue

**Comment by migue** [comment]
Thanks Alberto,

I will try to take a look and soon as we can: will contact you if I have
any doubt!

On 14 January 2016 at 19:40, Alberto Chaparro <notifications@github.com>
wrote:

> Hey @migue <https://github.com/migue>,
>
> I have just realized that this pull request seems to have the same purpose
> that mine here:
> #635 <https://github.com/migue/liferay-portal/pull/635>
>
> Please, take that into account after selecting one to solve the issue.
>
> Thanks!
> @migue <https://github.com/migue>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/migue/liferay-portal/pull/633#issuecomment-171734248>.
>



-- 
Un saludo,

Migue

http://migue.github.io

**Comment by cgoncas** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34627. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
