### PR TITLE
LPS-68775 Upgrade organizations' type_field following specs on LPS-62209

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
cc/ @jorgeferrer: I believe this was missed on https://github.com/JorgeFerrer/liferay-portal/pull/635

**Comment by mdelapenya** [comment]
ci:reopen

**Comment by JorgeFerrer** [comment]
Hey Manuel,

Thanks for finding and fixing this. Can you send it to Drew or Pei-Jung once you are done?

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/pei-jung/liferay-portal/pull/150. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
