### PR TITLE
LPS-70392

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Hey guys,

I am not sure this is the proper fix.

The legacy plugins don't use the new mechanism of upgrades, so I am not sure this should be necessary.

In case you've converted a legacy plugin to the new model, you should write your upgrades accordingly.

Would be nice if you could give a more detailed example of you use case, maybe I am missing something

**Comment by yuhai** [comment]
Hi migue,

The legacy plugins(for example) use the mechanism of upgrades, only miss some upgrade steps. Please  refer to the explanaion and example from https://github.com/hhuijser/liferay-portal/pull/2779#issue-204822295

In addition, if the fix logic is right, please also refer to https://github.com/hhuijser/liferay-portal/pull/2779#issuecomment-277876626 regarding SF commit.

Regards,
Hai

**Comment by migue** [comment]
After our conversation @yuhai is going to resend the pull with a different fix

**Pull request closed without merging**
