### PR TITLE
LPS-59594 Partitioning tool (pre-eliminary version)

### PR DESCRIPTION
**Pull request by mdelapenya**
This tool supports MySQL and PostgreSQL at this moment, and is a pre-eliminary version of definitive tool.

Please review it and change whatever you find. Thanks

### CODE REVIEW

**Comment by migue** [comment]
Ran out of time today, sorry; will try to take a look tomorrow early in the morning!

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Closed as we've already gone through it on Skype/Slac

**Pull request closed without merging**
