### PR TITLE
LPS-69276 Use decoupled SQLTransformer logic from DBMS transformers

### PR DESCRIPTION
**Pull request by mdelapenya**
SQLTransformer already knows how to cast long texts

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:reopen

**Comment by mdelapenya** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45439. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
