### PR TITLE
LPS-64737 Prepare interfaces and base classes for Oracle support

### PR DESCRIPTION
**Pull request by mdelapenya**
This PR is required by the EE modules to work (see https://github.com/migue/liferay-portal-ee/pull/19). Once it's merged and ported to EE branch, then we can continue and push those modules

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
@mdelapenya will resend this according to our conversation

**Pull request closed without merging**
