### PR TITLE
LPS-59594 Partitioning tool: MySQL + PostgreSQL + Oracle

### PR DESCRIPTION
**Pull request by mdelapenya**
Currently working on Sybase and DB2

### CODE REVIEW

**Comment by mdelapenya** [comment]
@migue, it fails because of the SourceFormatter, which wants code to use StringUtil.toUpperCase, which is not the case, as we want to be portal-independent

**Comment by migue** [comment]
No problem,

Will try to take a look later tonight or, probably, early in the morning.

Trying to catch up with the upcoming lessons I am teaching at the University, sorry about the delay

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
Is this a false positive?
````
Caused by: java.lang.ClassNotFoundException: com.liferay.hot.deploy.jmx.listener.mbean.manager.PluginMBeanManager
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 50 more
```

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
