### PR TITLE
LPS-61295: Upgrade Release_ table, so legacy plugins migrated as modules can be upgraded

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/cgoncas/liferay-portal/pull/177. [See changes here.](https://github.com/migue/liferay-portal/compare/dfc7989~2...dfc7989) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
