### PR TITLE
[TECHNICAL-SUPPORT] LPS-71983

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @SamZiemer

### CODE REVIEW

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Hello folks,

Is this strictly required? This is the implementation of the `getSchema` method in the Postgres' JDBC driver

```java
  public String getSchema() throws SQLException {
    checkClosed();
    Statement stmt = createStatement();
    try {
      ResultSet rs = stmt.executeQuery("select current_schema()");
      try {
        if (!rs.next()) {
          return null; // Is it ever possible?
        }
        return rs.getString(1);
      } finally {
        rs.close();
      }
    } finally {
      stmt.close();
    }
  }
```

**Comment by jonathanmccann** [comment]
@migue The first time through, PostgreSQL was returning the incorrect schema. This coupled with the fact that we do the same thing in UpgradePostgreSQL (https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/upgrade/v7_0_0/UpgradePostgreSQL.java#L52-L63) made us think this was necessary.

We will take another look at PostgreSQL and try to see why it's not returning the correct schema out of the box.

**Comment by SamZiemer** [comment]
@migue After debugging the connection.getSchema() method, the problem seems to be with the implementation in the driver. It is not actually using the method you listed, instead, it is using a similar method that runs the query "SHOW search_path", rather than "SELECT current_schema".

This returns a string "$user",public. However, only the first part "$user" is returned with getSchema, which leads to the problems we are seeing.

**Comment by migue** [comment]
It was a bug in an older version of the PostgreSQL driver: it was fixed here https://github.com/pgjdbc/pgjdbc/pull/356 and it was included in the release REL9_4_1202 (we are currently shipping the 9.4.0.build-1201)

I am not sure about the policy to update libraries in a fix pack so we can do the following:

* Merge the current approach (with the if statement) and backport it.
* Once it's been already merged and backported, remove the if condition and update the PostgreSQL driver we're shipping by default.

Let me know what you think.

**Comment by jonathanmccann** [comment]
That sounds like the best course of action to me.

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48547. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
