### PR TITLE
LPS-55715 Close database statement

### PR DESCRIPTION
**Pull request by achaparro**
Thanks!

### CODE REVIEW

**Comment by achaparro** [comment]
Tested and it works!

**Comment by achaparro** [comment]
Hey @migue,

could you take a look a this change? Basically these are the modication we agreed after discarding to use a batch process.

Thanks.

**Comment by migue** [comment]
ci:retest

**Comment by achaparro** [comment]
Closed and rebased here:
https://github.com/migue/liferay-portal/pull/483

Thanks!

**Pull request closed without merging**
