### PR TITLE
LPS-67131 Get rid of extra query for MySQL and Oracle

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/41665. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
