### PR TITLE
LPS-69197 Set a timeout to avoid freezes during startup if a initialBundle is lock

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45579. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
