### PR TITLE
LPS-42120 Decouple plugin validation from deployment, so we are able to not deploy if there are more than one valid auto deploy listener

### PR DESCRIPTION
**Pull request by mdelapenya**
Last commit of this pull is related to a related story: LPS-62838

### CODE REVIEW

**Comment by mdelapenya** [comment]
The error is related to OSGi:
```
Caused by: org.osgi.framework.BundleException: Unable to resolve com.liferay.registry.test [6](R 6.0): missing requirement [com.liferay.registry.test [6](R 6.0)] osgi.wiring.package; (osgi.wiring.package=com.liferay.registry.internal) Unresolved requirements: [[com.liferay.registry.test [6](R 6.0)] osgi.wiring.package; (osgi.wiring.package=com.liferay.registry.internal)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)
	at org.apache.felix.framework.Felix.loadBundleClass(Felix.java:1904)
	... 118 more
```

**Comment by mdelapenya** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
ci:retest

**Pull request closed without merging**
