### PR TITLE
LPS-63736

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/36733

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/36744. [See changes here.](https://github.com/migue/liferay-portal/compare/87879e1~2...87879e1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/36757. [See changes here.](https://github.com/migue/liferay-portal/compare/58c0593~1...58c0593) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
