### PR TITLE
LPS-68195 Connection is closed during document download

### PR DESCRIPTION
**Pull request by IstvanD**
Hey Miguel,

Some time ago you suggested as a solution for issue [LPS-68195](https://issues.liferay.com/browse/LPS-68195) to embed the content of `com.liferay.portal.webserver.WebServerServlet.service(HttpServletRequest request, HttpServletResponse response)`  in a transaction., and it solved it indeed.

Do you think this could be also suitable for master?

If so, please review the pull eg. send in to the appropriate reviewer.

Thank you in advance!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:reopen

**Comment by IstvanD** [comment]
The source formatting error message

**java.lang.Exception: There should be a line break after 'path,': ../../../portal-impl/src/com/liferay/portal/webserver/WebServerServlet.java 1368**

appears regardless of the alignment of the `sendDocumentLibrary` parameters in line 1368.
I left line 1368 the way *ant format-source* formatted it.

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Ran out of time today; will take a look tomorrow morning ...

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45044. [See changes here.](https://github.com/migue/liferay-portal/compare/f6692e8~2...f6692e8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
