### PR TITLE
Fix minor upgrade issues

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37627. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37633. [See changes here.](https://github.com/migue/liferay-portal/compare/6a6f7c9~1...6a6f7c9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
