### PR TITLE
LPS-63740

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@migue  Brian wanted us to send to you first.

@david-truong fyi

**Comment by migue** [comment]
Will take a look to it tomorrow, guys

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38242. [See changes here.](https://github.com/migue/liferay-portal/compare/afd9e5a~1...afd9e5a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
