### PR TITLE
LPS-55475 Add a message to inform all the rows that can't be updated with a valid companyId

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
I've closed this pull, because the tests weren't being executed. I've opened https://github.com/migue/liferay-portal/pull/511.

This pull is rebased from today, and now the test are being executed ;)

Thank you, @migue

**Comment by migue** [comment]
ci:retest

**Pull request closed without merging**
