### PR TITLE
LPS-65389 Show the Display portlet mapping in the UI

### PR DESCRIPTION
**Pull request by adolfopa**
@migue In the first two commits I've changed the behaviour of the `getFriendlyURLMapping` and `getFriendlyURLMapperInstance` methods.

`getFriendlyURLMapping` used to return the value of the `friendly-url-mapping` property declared in the Portlet component. The thing is, that property is almost always unset in the portlet, it is usually defined in friendly url mappers, and so, almost 100% of the time that method returned `null`.

Not sure if that behaviour was intentional, but I've changed it so that it asks the mapper (if any) for the current friendly url mapping. I believe the original behaviour is not very useful.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
Sorry, this is rebased on top of the wrong PR. Will resend.

**Comment by adolfopa** [comment]
False alarm, everything is ok :-)

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
I've pushed forced (wrong LPS number in one of the commits).

**Comment by adolfopa** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39185. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
