### PR TITLE
LPS-67296 Apply sql transformer functions approach, using Lambdas

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Is there any reason why the tests for the commercial databases are not included in the pull?

**Comment by mdelapenya** [comment]
Yes! I wrote this `Tests cannot be written because the COMMERCIAL DB object is not present in this branch. Let's wait until merged into ee-7.0.x` on each commit message related to them.

**Comment by migue** [comment]
Github interface doesn't show the whole message commit, sorry (I was looking at the pull here)

I don't think this should be a problem, right? Your test could have an assumption on the expected database

**Comment by mdelapenya** [comment]
That's right... I'll can investigate how to achive it ;)

Thanks @migue

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47404. [See changes here.](https://github.com/migue/liferay-portal/compare/60de1db37b77~4...60de1db37b77) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
