### PR TITLE
LPS-59594 MySQL Support + test support

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
@mdelapenya ran out of time today, sorry

Everything looks good to me after a quick look through the code, but I would like to avoid the "base class" pattern for the tests at least.

We can talk tomorrow about it.

Thanks a lot!

PS: I will keep it open

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35349. [See changes here.](https://github.com/migue/liferay-portal/compare/4451dd7~1...4451dd7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by migue** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35350. [See changes here.](https://github.com/migue/liferay-portal/compare/fa79e70~2...fa79e70) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
