### PR TITLE
LPS-53736 Add DDL dependencies to portal-tools module

### PR DESCRIPTION
**Pull request by marcellustavares**
Hey @migue, this is a partial extraction of DDL out of core, I was wondering if you could review this part. I've removed the api, services and tests, it's still missing the web.

The portal is not compiling b/c it references DDL API in some places but I'm not sure hot to fix them, I've added the whole API to the Export-Packages but maybe I'm missing something.

Also, tests are failing. I've one unit in particular that's if failing on a `new` call (`DDLRecordSetImplTest`) if you could check this it would be awesome.

Please, could you send back to me?

Thanks a lot Miguel!

### CODE REVIEW

**Comment by migue** [comment]
Marcellus,

I've been at a conference and holidays, just trying to catch up ... I took a quick overview today but I need to go deeper.

Do you want to Skype/Hangout and share your doubts with me?

Sorry for the delay!!

**Comment by marcellustavares** [comment]
I'd be nice, can I ping you tomorrow morning?
Em 05/03/2015 18:44, "Miguel Ángel Pastor Olivar" <notifications@github.com>
escreveu:

**Comment by migue** [comment]
Sure thing,

I will only available until 14:00 (Local time) because I have to pick up my
son at the school :D

On 5 March 2015 at 22:49, Marcellus Tavares <notifications@github.com>
wrote:

> I'd be nice, can I ping you tomorrow morning?
> Em 05/03/2015 18:44, "Miguel Ángel Pastor Olivar" <
> notifications@github.com>
> escreveu:
>
> > Marcellus,
> >
> > I've been at a conference and holidays, just trying to catch up ... I
> took
> > a quick overview today but I need to go deeper.
> >
> > Do you want to Skype/Hangout and share your doubts with me?
> >
> > Sorry for the delay!!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/migue/liferay-portal/pull/428#issuecomment-77458641
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/migue/liferay-portal/pull/428#issuecomment-77459481>.
>



-- 
Un saludo,

Migue

http://migue.github.io

**Comment by marcellustavares** [comment]
Hey Miguel, I had some problems this morning I couldn't come to the office.
I'll ping you on Monday.

Sorry about that.

Regards,

On Thu, Mar 5, 2015 at 7:42 PM, Miguel Ángel Pastor Olivar <
notifications@github.com> wrote:

> Sure thing,
>
> I will only available until 14:00 (Local time) because I have to pick up my
> son at the school :D
>
> On 5 March 2015 at 22:49, Marcellus Tavares <notifications@github.com>
> wrote:
>
>
> > I'd be nice, can I ping you tomorrow morning?
> > Em 05/03/2015 18:44, "Miguel Ángel Pastor Olivar" <
> > notifications@github.com>
> > escreveu:
> >
> > > Marcellus,
> > >
> > > I've been at a conference and holidays, just trying to catch up ... I
> > took
> > > a quick overview today but I need to go deeper.
> > >
> > > Do you want to Skype/Hangout and share your doubts with me?
> > >
> > > Sorry for the delay!!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/migue/liferay-portal/pull/428#issuecomment-77458641
> > >.
> >
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/migue/liferay-portal/pull/428#issuecomment-77459481
> >.
> >
>
>
>
> --
> Un saludo,
>
> Migue
>
> http://migue.github.io
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/migue/liferay-portal/pull/428#issuecomment-77468435>.
>



-- 
Marcellus Tavares
Software Engineer

Liferay Inc.
Enterprise. Open Source. For Life
www.liferay.com

**Pull request closed without merging**
